
swagger: "2.0" 
info:
  description: "逗比网后台"
  # 当前API接口的版本号
  version: "1.0.0"
  # API接口名称
  title: "逗比网后台"
  
  termsOfService: ""
  contact:
    email: "kanseefoil@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
# 后台API主机的网址
host: "localhost:3010"
# 基础统一的路径
basePath: "/"

schemes:
- "http"
- "https"

paths: 
  /authentication/registry:
    post:
      summary: "注册接口"
      parameters: 
        - name: user
          in: body
          required: true
          description: task object
          schema: 
            type: object
            properties:
              userName:
                type: string
              password:
                type: string
      responses:
        200:
          description: 注册成功
        400:
          description: valid
        500:
          description: 服务器问题
  /authentication/uploadUserHeader:
    post:
      tags:
      - "用户上传头像"
      summary: ""
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "file"
        in: "formData"
        description: "file to upload"
        required: false
        type: "file"
      responses:
        200:
          description: "successful operation"
  /ws:
    get:
      tags:
      - "默认测试主机是否畅通"
      summary: "Find pet by ID"
      description: "Returns a single pet"

      responses:
        200:
          description: 响应成功
          schema:
            $ref: "#/definitions/User"
        400:
          description: valid
        500:
          description: 服务器问题
  /ws/about:
    get:
      tags:
      - "默认测试主机是否畅通"
      summary: "Find pet by ID"
      description: "Returns a single pet"

      responses:
        200:
          description: 响应成功
          schema:
            $ref: "#/definitions/User"
        400:
          description: valid
        500:
          description: 服务器问题
definitions:
  User:
    type: object
    properties: 
      name :
        type : string

